### PR TITLE
Prepare for shipping to npm, don't commit ts types

### PR DESCRIPTION
**Pull request by t3chguy**
For https://github.com/vector-im/element-web/issues/21166
For https://github.com/vector-im/element-web/issues/22089

### CODE REVIEW

**Review by turt2live — APPROVED** [review]
lgtm - leaving it to you to review my commits

**Comment by turt2live** [comment]
as of this comment, the package is published as https://www.npmjs.com/package/@matrixdotorg/analytics-events from this branch.

**Comment by turt2live** [comment]
and now as https://www.npmjs.com/package/@matrix-org/analytics-events with the fixed scope

**Review by ismailgulek — APPROVED** [review]
Lgtm!

**Pull request merged**
