### PR TITLE
Add some missing periods.

### PR DESCRIPTION
**Pull request by bmarty**
The generated code is analyzed by Detekt when imported in the Element Android project, and the Kdoc content is (or rather will be) checked. Sentences have to end with a period.

### CODE REVIEW

**Comment by t3chguy** [comment]
If this is something we should adhere to then please write it into the contributing guide for this repo

**Comment by bmarty** [comment]
> If this is something we should adhere to then please write it into the contributing guide for this repo

Good point: c438b8c

**Review by pixlwave — APPROVED** [review]

**Comment by pixlwave** [comment]
One question, how come only the Kotlin files are updated?

**Comment by bmarty** [comment]
> One question, how come only the Kotlin files are updated?

My bad, I am calling `yarn build:kt2` to be faster.

c1e0c1aca4eeeb2160c371c1547b1a014529926c contains all the generated files.

**Comment by pixlwave** [comment]
LGTM 👌

**Review by ouchadam — APPROVED** [review]

**Pull request merged**
